REDIS_HOST: redis-{{ env }}.daws86s-akhil.shop
MONGODB_HOST: mongodb-{{ env }}.daws86s-akhil.shop
CATALOGUE_HOST: catalogue.backend-alb-{{ env }}.daws86s-akhil.shop
MYSQL_HOST: mysql-{{ env }}.daws86s-akhil.shop
CART_HOST: cart.backend-alb-{{ env }}.daws86s-akhil.shop
USER_HOST: user.backend-alb-{{ env }}.daws86s-akhil.shop 
RABBITMQ_HOST: rabbitmq-{{ env }}.daws86s-akhil.shop
SHIPPING_HOST: shipping.backend-alb-{{ env }}.daws86s-akhil.shop
PAYMENT_HOST: payment.backend-alb-{{ env }}.daws86s-akhil.shop