- name: import app setup role 
  ansible.builtin.import_role:
    name: common
    tasks_from: appsetup.yaml

- name: import app setup role 
  ansible.builtin.import_role:
    name: common
    tasks_from: python.yaml

- name: restart sshd
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: latest
  loop:
  - openssl
  - openssl-libs
  - openssh
  - openssh-server
  - openssh-clients

- name: import systemd setup 
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd.yaml